# Lab 1 : NUMPY ARRAY AND IT'S FEATURE 

In [4]:
# Create a simple numpy array (1D numpy array)
import numpy as np
arr = np.array([10,23,32,12,10])
print(arr)

[10 23 32 12 10]


In [6]:
# 2D array
arr2d1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2d1)
arr2d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# Create 3D array 
arr3d = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]


In [10]:
# Dimension of an array 
a = np.array([1,2,3,4,5])
arr2d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3d = np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(a.ndim)
print(arr2d2.ndim)
print(arr3d.ndim)

1
2
3


In [11]:
# Create an array 5 dimension
d = np.array([1,2,3,4],ndmin = 5)
print(d)
print(d.ndim)

[[[[[1 2 3 4]]]]]
5


In [12]:
# Access element of an array 
a = np.array([10,25,35,11,8,17])
print(a[2])

35


In [13]:
# Access element of an array (First Row, Second Column)
b = np.array([[1,2,3,4],[5,6,7,8]])
print("The second element on the first row is",b[0,1])

The second element on the first row is 2


In [15]:
# Slicing 
arr = np.array([0,1,2,3,4,5,6,7,8,9,10])
print(arr[0:5])
print(arr[::2])

[0 1 2 3 4]
[ 0  2  4  6  8 10]


### TASK : Create a single 6D array and perform slicing

In [16]:
arr2 = np.array([1,2,3,4,5,6,7,8], ndmin = 6)
print(arr2)
print(arr2[:,:,:,:,:,0:5])

[[[[[[1 2 3 4 5 6 7 8]]]]]]
[[[[[[1 2 3 4 5]]]]]]


In [17]:
# Shape of an array 
z = np.array([[1,2,3,4],[5,6,7,8]])
print(z.shape)

(2, 4)


In [18]:
# Converting the 1D array to 2D array
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
NewArray = x.reshape(4,3)
print(NewArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [24]:
# Convert 2D to 1D
y = np.array([[1,2,3,4],[5,6,7,8]])
print("Before : \n",y)
newp = y.reshape(-1)
print("\nAfter : \n",newp)

Before : 
 [[1 2 3 4]
 [5 6 7 8]]

After : 
 [1 2 3 4 5 6 7 8]


In [25]:
# for loop
for i in range (5) :
    print(i)

0
1
2
3
4


In [26]:
# Iterate in an array 
s = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np.nditer(s) : 
    print(x)

1
2
3
4
5
6
7
8
9
10


In [27]:
# Join the two array 
ar1 = np.array([1,2,3])
ar2 = np.array([4,5,6])
f = np.concatenate((ar1,ar2))
print(f)

[1 2 3 4 5 6]


In [28]:
# Join 
j1 = np.array([1,2,3,4,5])
j2 = np.array([6,7,8,9,10])
fj = np.stack((j1,j2),axis = 1)
print(fj)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [29]:
# Search element 
se = np.array([10,23,34,25])
res = np.where(se == 23)
print(res)

(array([1]),)


In [30]:
# Search for even element 
res = np.where(se%2 == 0)
print(res)

(array([0, 2]),)


In [31]:
# Sort
sr = np.array([3,1,4,6,5])
print(np.sort(sr))

[1 3 4 5 6]


In [32]:
# Filtering
fi = np.array([1,2,3,4])
x = [True, False, False, True]
newfi = fi[x]
print(newfi)

[1 4]
